[package]
name = "talpid-openvpn-plugin"
version = "2020.4.0-beta4"
authors = ["Mullvad VPN"]
description = "OpenVPN shared library plugin for relaying OpenVPN events to talpid_core"
license = "GPL-3.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
err-derive = "0.2.1"
log = "0.4"
env_logger = "0.7"
jsonrpc-client-core = { git = "https://github.com/mullvad/jsonrpc-client-rs", rev = "68aac55b" }
jsonrpc-client-ipc = { git = "https://github.com/mullvad/jsonrpc-client-rs", rev = "68aac55b" }
tokio-reactor = "0.1"
tokio = "0.1"
futures = "0.1"

openvpn-plugin = { git = "https://github.com/mullvad/openvpn-plugin-rs", branch = "auth-failed-event", features = ["serde", "log"] }
talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Mullvad VPN AB"
LegalCopyright = "(c) 2020 Mullvad VPN AB"
InternalName = "talpid-openvpn-plugin"
OriginalFilename = "talpid_openvpn_plugin.dll"
